service: serverless-auth

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    USERS_TABLE: Users
    JWT_SECRET: mySuperSecretKey

functions:
  registerUser:
    handler: registerUser.handler
    events:
      - http:
          path: register
          method: post

  loginUser:
    handler: loginUser.handler
    events:
      - http:
          path: login
          method: post

  verifyOTP:
    handler: verifyOTP.handler
    events:
      - http:
          path: verify-otp
          method: post
